### PR TITLE
Added clarifying comment 

### PR DESCRIPTION
**Pull request by lmcm18**
https://flatiron.atlassian.net/browse/CO-501

Changelog: 

1. Fixed some typos 

2. Added clarifying comment regarding output of `model.evaluate` by having students run `model.metrics_names` to see what the output of `model.evaluate` means.

### CODE REVIEW

**Comment by erdosn** [comment]
@lmcm18 there's a conflict.

**Comment by mathymitchell** [comment]
Looks good in general and approving; found a small grammatical typo that still exists:

"This because the training set is slightly different! You removed 1000 instances for validation!"

(Missing an is) So, should be something like this:

"This is because the training set is slightly different! You removed 1000 instances for validation!"

**Comment by lmcm18** [comment]
@erdosn  fixed the merge conflicts.

**Comment by lmcm18** [comment]
@mathymitchell fixed the grammar mistake

**Pull request merged**
